#!/usr/bin/env bash

set -ex

ruby --version
gem --version
cd /src
gem install bundler -v 2.1.4
bundle install --deployment
bundle --version
bundle list
gem update bundler
if [[ -n "$RUBYGEMS_UPDATE" ]]; then
  gem update --system
  gem --version
fi
bundle --version
bundle list
