#!/usr/bin/env bash

set -ex

ruby --version
gem --version
cd /src
gem install bundler -v 2.1.4
bundle install --deployment
bundle --version
bundle list
gem update bundler
bundle --version
bundle list
